image: golang:1.17

stages:
  - install
  - pre_build
  - build
  - post_build

install:
  stage: install
  script:
    - echo "Installing dependencies..."

pre_build:
  stage: pre_build
  script:
    - echo "Fetching required Go modules..."
    - go mod download

build:
  stage: build
  script:
    - echo "Building the project..."
    - go build -v ./...

post_build:
  stage: post_build
  script:
    - echo "Running tests..."
    - go test -v ./...