image: docker:latest

services:
  - docker:dind

stages:
  - build
  - lint
  - test

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build --target build-stage --tag my-app-build:latest .
    - docker build --target run-test-stage --tag my-app-test:latest .
    - docker build --tag my-app:latest .

lint:
  stage: lint
  dependencies:
    - build
  script:
    - docker run --rm my-app-build:latest golangci-lint run

test:
  stage: test
  dependencies:
    - build
  script:
    - docker run --rm my-app-test:latest
