version: 2.1

jobs:
  build-and-test:
    docker:
      - image: docker:19.03.12
    steps:
      - setup_remote_docker:
          version: 19.03.12
          docker_layer_caching: true
      - checkout
      - run:
          name: Install Docker Buildx and curl
          command: |
            apk add --no-cache curl
            mkdir -p ~/.docker/cli-plugins/
            curl -SL https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
            chmod +x ~/.docker/cli-plugins/docker-buildx
            docker buildx create --use
            docker buildx inspect --bootstrap
      - restore_cache:
          keys:
            - docker-layer-cache-{{ .Branch }}-{{ .Revision }}
            - docker-layer-cache-
      - run:
          name: Build and Test Docker Image
          command: |
            docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache -f Dockerfile.multistage --target=run-test-stage -t $CIRCLE_PROJECT_REPONAME:test .
            docker run --rm $CIRCLE_PROJECT_REPONAME:test nosetests -v --with-xunit --xunit-file=/circle_artifacts/nosetests.xml --with-coverage --cover-html --cover-html-dir=/circle_artifacts/coverage_html/
      - save_cache:
          key: docker-layer-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - /tmp/.buildx-cache
      - store_artifacts:
          path: /circle_artifacts
          destination: coverage_html

  release:
    docker:
      - image: docker:19.03.12
    steps:
      - setup_remote_docker:
          version: 19.03.12
          docker_layer_caching: true
      - checkout
      - run:
          name: Install Docker Buildx and curl
          command: |
            apk add --no-cache curl
            mkdir -p ~/.docker/cli-plugins/
            curl -SL https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
            chmod +x ~/.docker/cli-plugins/docker-buildx
            docker buildx create --use
            docker buildx inspect --bootstrap
      - restore_cache:
          keys:
            - docker-layer-cache-{{ .Branch }}-{{ .Revision }}
            - docker-layer-cache-
      - run:
          name: Build and Push Docker Image
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --push -t ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG} .

workflows:
  build-test-and-release:
    jobs:
      - build-and-test
      - release:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/
