version: 2.1

jobs:
  build-and-test:
    docker:
      - image: docker:20.10.7
    steps:
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - checkout
      - run:
          name: Install Docker Buildx and curl
          command: |
            apk add --no-cache curl
            mkdir -p ~/.docker/cli-plugins/
            curl -SL https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
            chmod +x ~/.docker/cli-plugins/docker-buildx
            docker buildx create --use
            docker buildx inspect --bootstrap
      - restore_cache:
          keys:
            - docker-layer-cache-{{ .Branch }}-{{ .Revision }}
            - docker-layer-cache-
      - run:
          name: Build Docker Image
          command: |
            docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --load -f Dockerfile.multistage --target=run-test-stage -t indtest:test .
      - run:
          name: Run Tests in Docker Container
          command: |
            docker run --name test-container indtest:test || echo "Tests failed"
      - run:
          name: Copy Test Logs and Results
          command: |
            docker cp test-container:/test-results/test-output.log test-output.log || echo "No test log found"
            docker cp test-container:/test-results/test-output.xml test-output.xml || echo "No test result XML found"
      - run:
          name: Remove Test Container
          command: |
            docker rm test-container || echo "No container to remove"
      - run:
          name: Display and Check Test Results
          command: |
            if grep -q "FAIL" test-output.log; then
              echo "Test failures detected:"
              grep -A 10 "FAIL" test-output.log  # Display the failures
              exit 1
            else
              echo "All tests passed."
            fi
      - run:
          name: Display All Test Logs
          command: cat test-output.log
      - save_cache:
          key: docker-layer-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - /tmp/.buildx-cache
      - store_test_results:
          path: test-output.xml
      - store_artifacts:
          path: test-output.log
          destination: test-output.log

  release:
    docker:
      - image: docker:20.10.7
    steps:
      - setup_remote_docker:
          version: 23.0.1
          docker_layer_caching: true
      - checkout
      - run:
          name: Install Docker Buildx and curl
          command: |
            apk add --no-cache curl
            mkdir -p ~/.docker/cli-plugins/
            curl -SL https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
            chmod +x ~/.docker/cli-plugins/docker-buildx
            docker buildx create --use
            docker buildx inspect --bootstrap
      - restore_cache:
          keys:
            - docker-layer-cache-{{ .Branch }}-{{ .Revision }}
            - docker-layer-cache-
      - run:
          name: Build and Push Docker Image
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --push -t ${DOCKERHUB_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG} .

workflows:
  build-test-and-release:
    jobs:
      - build-and-test
      - release:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/
